[project]
name = "django-advanced-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "django-q2>=1.8.0",
    "docutils>=0.22.3",
    "gunicorn>=23.0.0",
]
